### ISSUE TITLE
Readme notes

### ISSUE THREAD

**Issue by Arcanemagus** [fmontesi/linter-jolie#2]
Just wanted to bring to your attention if you haven't already found this out that the autocompletion stuff should be an [autocomplete-plus](https://github.com/atom/autocomplete-plus) plugin package.

Or you could integrate both services into `language-jolie` and when the user installs that they will automatically get linting and code snippets. [atom-typescript](https://atom.io/packages/atom-typescript) is an example of that model.

**Comment by fmontesi** [comment]
Thanks, we'll have a look at it when we're ready for autocompletion. 👍
