### ISSUE TITLE
"if" in comments is colored.

### ISSUE THREAD

**Issue by crashh** [fmontesi/linter-jolie#3]
See topic.

![Alt](https://cdn.pbrd.co/images/1Y9lMEUI.png)

**Comment by fmontesi** [comment]
I think it's because in general inline comments (//) are not in the grammar in grammars/jolie.cson. Once that's fixed, all keywords there should not get highlighted hopefully.

Ideas on how to do that properly are welcome. :-)

**Comment by mawolf** [comment]
I have created a pull request in the language-jolie repo

**Comment by fmontesi** [comment]
Awesome, thanks!
