### ISSUE TITLE
Link to the error does not work

### ISSUE THREAD

**Issue by bmaschio** [fmontesi/linter-jolie#5]
@fmontesi 

linter works fine and it highlights the correct error

![image](https://cloud.githubusercontent.com/assets/12083716/14844588/a9c0d514-0c58-11e6-9c90-260ca1767a2b.png)

yet when i double click on the link 

it does not open the correct file but instead it opens a new empty file atom application directory

![image](https://cloud.githubusercontent.com/assets/12083716/14844635/06386582-0c59-11e6-8f38-3f4b5a4dd1b4.png)

I think this is due to the fact that the path is expressed in relative terms

**Comment by fmontesi** [comment]
Can you reproduce this in other OSs? It works fine in my MacOS laptop.

**Comment by bmaschio** [comment]
No unfortunately

yet I add a log to the code

![image](https://cloud.githubusercontent.com/assets/12083716/14851598/37833950-0c81-11e6-8e94-8abfeed504e9.png)

and it seems to have the correct file

![image](https://cloud.githubusercontent.com/assets/12083716/14851632/705d849c-0c81-11e6-82c9-0b37134bc25f.png)

I think it maybe a problem at level of Issue reporting  
I also noticed that on the original file is not highlighted  like in the case of any other language

![image](https://cloud.githubusercontent.com/assets/12083716/14851861/e6d4bd1a-0c82-11e6-84b2-beb26dbcb387.png)

tnks

**Comment by bmaschio** [comment]
on the linter own tool the error are  reported in this way

```
  transform = ({level, message, rule, lineNumber, context, column}) ->
    message = "#{message}. #{context}" if context
    message = "#{message}. (#{rule})";

    # Calculate range to make the error whole line
    # without the indentation at begining of line
    indentLevel = TextEditor.indentationForBufferRow(lineNumber - 1)

    startCol = (TextEditor.getTabLength() * indentLevel)
    endCol = TextBuffer.lineLengthForRow(lineNumber - 1)

    range = [[lineNumber - 1, startCol], [lineNumber - 1, endCol]]

    return {
      type: if level is 'error' then 'Error' else 'Warning'
      text: message
      filePath: filePath
      range: range
    }
```

**Comment by fmontesi** [comment]
Not sure what's the difference, helpers.exec should be doing the same thing
(but I haven't checked).

**Comment by bmaschio** [comment]
@fmontesi 

I think I may have found out the reason why it does not not work  i thinkis a question of  the regular expression used to parse the message  I was wandering why also it is present / on the start of the file path could be somenthing to to with linux
Caused by: jolie.lang.parse.ParserException: /C:/Users/maschio/Documents/GitHub/MongoDBConnector/JolieTest/main_insert_test.ol:48: error: expected }. Found toke
n type UNDEF, token content undef 

thanks 

Balint

**Comment by fmontesi** [comment]
It's because the filename is basically converted to a URL in Jolie. (Think file://C:/Users/...etc...)
That's because some resources that are included may not be in the local filesystem, so we need a uniform representation (offered by URLs).

Maybe there's some Javascript API around that can convert it back to what we need in Atom?

**Comment by bmaschio** [comment]
there is not File under windows 
jolie.InterpreterException: jolie.lang.parse.ParserException: /C:/Progetti/SVN_D
EV/PortaleManutenzioneAndroid/MaintanceService/file:/Progetti/SVN_DEV/PortaleMan
utenzioneAndroid/MaintanceService/./public/interfaces/maintanaceServiceInterface
.iol:146: error: invalid type: AddMainLineResponse. Found token type COMMA

What if we put the check output into a nice tageted format such XML or into a structured output like JSON? I know is a silly idea

**Comment by fmontesi** [comment]
How would that help? It would still contain that path written like that, no? The problem seems to be that path string. :-\

**Comment by bmaschio** [comment]
I suppose in my silly mind it would help making it a bit more readable but yes I agree it would not solve the problem:  Why do you think the ParserExpeption has a behavior in linux 
jolie.InterpreterException: jolie.lang.parse.ParserException: /home/italianasoftware/microservices/testGenerici/testOSCommand.ol:15: error: 
and one in windows
jolie.InterpreterException: jolie.lang.parse.ParserException: /C:/Progetti/Dropb
ox/testGenerici/testOSCommand.ol:15: error: expected } 

I think i may have found where the problem is in the commandLineParser method GetOLStreamResult
where the souce is defined as 

`result.source = f.toURI().getSchemeSpecificPart();`

I did not want do dismantle the code so i did a simple code 

```
        File f = new File ("TestForUri.java").getAbsoluteFile();
        System.out.println(f.getAbsolutePath());
        System.out.println(f.toURI());
        System.out.println(f.toURI().getSchemeSpecificPart());
```

with the following result

```
C:\Users\maschio\Documents\NetBeansProjects\TestForUri\TestForUri.java
file:/C:/Users/maschio/Documents/NetBeansProjects/TestForUri/TestForUri.java
/C:/Users/maschio/Documents/NetBeansProjects/TestForUri/TestForUri.java
```

I am not sure this helps

**Comment by fmontesi** [comment]
Maybe Atom would understand it better if we passed file: too at the beginning?

Try adding

```
issue.filePath = "file:" + issue.filePath
```

Right before the final return `return issue` in https://github.com/fmontesi/linter-jolie/blob/master/lib/main.coffee

**Comment by fmontesi** [comment]
If that's the case, then we could change Jolie to give the full URI instead of just the scheme-specific part.

**Comment by bmaschio** [comment]
Shell I then modify jolie  GetOLStreamResult?

**Comment by fmontesi** [comment]
Depends on what the Atom patch reveals. Have you tried applying the line of code I mentioned in my comment? (`issue.filePath = ...`)

**Comment by bmaschio** [comment]
After some serious swearing  I have arrived to a script ( coffee script more like heroine script ) that looks like this

```
helpers = require 'atom-linter'
{ BufferedProcess } = require 'atom'

executablePath = "jolie"
pattern = ".+:\\s*(?<file>[^:]+):\\s*(?<line>\\d+):\\s*(?<type>error|warning)\\s*:(?<message>.+)"



module.exports =
  config: {}


 activate: ->
    require( "atom-package-deps" ).install( "linter-jolie" );

  provideLinter : ->
      parse =  (jolieCheckOuput, textEditor) ->
            return helpers.parse( jolieCheckOuput.stderr, pattern ,{ filePath: textEditor.getPath() } )
                .map ( issue ) ->          
                    [ [ lineStart, colStart ], [ lineEnd, colEnd ] ] = issue.range
                    issue.range = helpers.rangeFromLineNumber textEditor, lineStart, colStart
                    issue.filePath = textEditor.getPath()
                    return issue
      provider =
        grammarScopes: ['source.jolie']
        scope: 'file'
        lintOnFly: true    
        lint: (editor) =>
            filePath = editor.getPath()
            return helpers.exec( executablePath, [ "--check", editor.getPath() ], { stream: "both" } ).then ( data )-> 
                    parse data , editor
```

that seems to work

![image](https://cloud.githubusercontent.com/assets/12083716/17596576/61c2239c-5ff2-11e6-9a48-aea8199bc4be.png)

then when i click on the link i get the proper file opened and joy more joy i get also

![image](https://cloud.githubusercontent.com/assets/12083716/17596623/96f1b85c-5ff2-11e6-9849-cacf21c914d9.png)

what do you think

**Comment by fmontesi** [comment]
You're taking the file path from the editor. I suspect that this doesn't work for (errors that come from) included files that you have not currently opened in the editor. Does it?

**Comment by bmaschio** [comment]
No I had the entire project opened  is something to do on how it formats the Path in linux format

**Comment by bmaschio** [comment]
@fmontesi Shell we talk over skype or handout about this would be nice to have it working for the italian meeting what you think?

**Comment by fmontesi** [comment]
Absolutely! (Sent you an e-mail.)

**Comment by bmaschio** [comment]
what mail did you sent it ro i can not find it
Thank
B

**Comment by fmontesi** [comment]
Your address at Monrif.

Cheers,
Fabrizio

**Comment by fmontesi** [comment]
Looks like our problem lies in `URIParsingContext`, in method `sourceName`. I'm attempting a fix using `Paths` from the standard library. Will commit soon.

**Comment by fmontesi** [comment]
Pushed. Can you try? You need to update both Jolie from git and `linter-jolie` in Atom.

**Comment by bmaschio** [comment]
@fmontesi 
Jolie check works fine 

![image](https://cloud.githubusercontent.com/assets/12083716/20343669/97f22270-abef-11e6-90f6-87b3df006c44.png)

but we still have the same problem

![image](https://cloud.githubusercontent.com/assets/12083716/20343655/7f76afa4-abef-11e6-9417-cd5df740a0ee.png)

![image](https://cloud.githubusercontent.com/assets/12083716/20343715/c85fc30e-abef-11e6-9f9d-8bb889859a8d.png)

it does kill the C:\

**Comment by fmontesi** [comment]
It's the regular expression in linter-jolie, checking..

**Comment by bmaschio** [comment]
@fmontesi 

the probably the problem in the [^:] this kind of is a problem under windows can we not add some token like <C:\pippo\pluto\paperino.ol> in the output of the url

**Comment by fmontesi** [comment]
Hi Balint, try now! Update again both linter-jolie and jolie.

**Comment by bmaschio** [comment]
@fmontesi 

with the source file it fantastically well 

but with the include files is missing the correct path when using jolie --check filename.ol

![image](https://cloud.githubusercontent.com/assets/12083716/20348929/53abc0ee-ac08-11e6-83f0-01e45f139f83.png)

C:\Progetti\SVN_DEV\RilevazioneTimbrature\AccountManager\leonardo>jolie --check
leonardo.ol
jolie.lang.parse.ParserException: \Progetti\SVN_DEV\RilevazioneTimbrature\Accoun
tManager\leonardo.\public\interfaces\HttpTimbratureInterface.iol:13: error: exp
ected type name. Found token type RCURLY
        at jolie.lang.parse.AbstractParser.throwException(AbstractParser.java:24
1)
        at jolie.lang.parse.AbstractParser.assertIdentifier(AbstractParser.java:
210)
        at jolie.lang.parse.AbstractParser.eatIdentifier(AbstractParser.java:196
)
        at jolie.lang.parse.OLParser.parseSubTypes(OLParser.java:303)
        at jolie.lang.parse.OLParser.parseType(OLParser.java:274)
        at jolie.lang.parse.OLParser.parseTypes(OLParser.java:245)
        at jolie.lang.parse.OLParser._parse(OLParser.java:209)
        at jolie.lang.parse.OLParser.parseInclude(OLParser.java:702)
        at jolie.lang.parse.OLParser._parse(OLParser.java:202)
        at jolie.lang.parse.OLParser.parse(OLParser.java:183)
        at jolie.Interpreter.buildOOIT(Interpreter.java:1220)
        at jolie.Interpreter.init(Interpreter.java:1033)
        at jolie.Interpreter.run(Interpreter.java:1108)
        at jolie.Jolie.main(Jolie.java:60)

thanks

Balint

**Comment by fmontesi** [comment]
Looks like a problem in libjolie, I'll check it tomorrow.

**Comment by fmontesi** [comment]
I've attempted a fix, but I can't test it on Windows. Please update libjolie and try again.

**Comment by bmaschio** [comment]
@fmontesi 

It works fantastically well  great job

It was tested on window 7 professional  iwill try it on windows 10 tonight for issue #4 i think you can close this issue

Thanks 
B

**Comment by fmontesi** [comment]
Great! :+1:
