### ISSUE TITLE
Error if more then a  file opened in Atom

### ISSUE THREAD

**Issue by bmaschio** [fmontesi/linter-jolie#6]
The following linter command gives a  range error

`issue.range = helpers.rangeFromLineNumber editor, lineStart, colStart`
 gives the following error 

![image](https://cloud.githubusercontent.com/assets/12083716/17372208/1bdf1cfe-59a3-11e6-83bd-0073a27b1944.png)

This is given by the following reasons 
- At the starting of the editor all the files are processed together 
- If in fileA the error is present at line 100 but the focused file has only 80 lines the editor gives the out of range errror

I have removed the line above and it seems to have no negative effect on the behavior, what is the reason to have that line?
Thanks
Balint

**Comment by fmontesi** [comment]
That line calculates the length of the line to be highlighted in the text. We can apply two fixes:
- remove the last parameter, i.e., switch to `issue.range = helpers.rangeFromLineNumber editor, lineStart`
- catch the Error from `rangeFromLineNumber`, in which case we just do not modify `issue`.

About the second item: `rangeFromLineNumber` seems to throw an `Error` when it doesn't like our input:

https://github.com/steelbrain/atom-linter/blob/master/src/index.js

We could just catch that.

**Comment by Arcanemagus** [comment]
You might also look into why the invalid input is being generated in the first place 😉.

That check was put in there specifically to catch bugs in linters and has resulted in many fixes to ESLint stylelint and flake8 that I know of.
